# Generated by Django 2.2 on 2019-04-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokes',
            name='joke_title',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
    ]
